# Generated by Django 4.2.6 on 2023-10-29 19:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("apps_catalogs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("address", models.CharField(blank=True, max_length=150, null=True)),
                (
                    "city_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_address",
                        to="apps_catalogs.city",
                    ),
                ),
                (
                    "state_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="state_address",
                        to="apps_catalogs.state",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección",
                "verbose_name_plural": "Direcciones",
            },
        ),
    ]
